name: Custom Build

on: workflow_dispatch

jobs:

  nightly:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout develop
        uses: actions/checkout@v4
        with:
          ref: develop

      - uses: './.github/actions/reusable-prepare-peertube-build'
        with:
          node-version: '18.x'

      - name: Build
        run: npm run nightly

      - name: Upload release file
        uses: actions/upload-artifact@v4
        with:
          name: peertube-build
          path: PeerTube/*.tar.xz
